CREATE SEQUENCE IF NOT EXISTS group_infos_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE address_title
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    CONSTRAINT pk_address_title PRIMARY KEY (id)
);

CREATE TABLE city
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(50)                             NOT NULL,
    description        VARCHAR(255),
    country_id         BIGINT,
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE close_reason
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_close_reason PRIMARY KEY (id)
);

CREATE TABLE collection_frequency
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    country_id         BIGINT                                  NOT NULL,
    frequency_id       BIGINT                                  NOT NULL,
    project_info_id    BIGINT                                  NOT NULL,
    status_id          BIGINT,
    description        VARCHAR(255),
    CONSTRAINT pk_collection_frequency PRIMARY KEY (id)
);

CREATE TABLE contact_info
(
    id                  BIGINT                      NOT NULL,
    created_by          BIGINT,
    created_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by    BIGINT,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    contact_no          VARCHAR(20)                 NOT NULL,
    contact_no_optional VARCHAR(255),
    member_info_id      BIGINT,
    CONSTRAINT pk_contact_info PRIMARY KEY (id)
);

CREATE TABLE country
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            BIGINT,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by      BIGINT,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    name                  VARCHAR(50)                             NOT NULL,
    code                  VARCHAR(10)                             NOT NULL,
    short_name            VARCHAR(3),
    short_code            VARCHAR(255),
    calling_code          VARCHAR(10)                             NOT NULL,
    has_operation         BOOLEAN,
    local_currency_name   VARCHAR(50)                             NOT NULL,
    foreign_currency_name VARCHAR(50)                             NOT NULL,
    minimum_denomination  FLOAT                                   NOT NULL,
    time_zone             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE country_office_hierarchy
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by             BIGINT,
    created_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by       BIGINT,
    last_modified_date     TIMESTAMP WITHOUT TIME ZONE,
    office_hierarchy_level INTEGER,
    country_of_office_id   BIGINT                                  NOT NULL,
    effective_date         TIMESTAMP WITHOUT TIME ZONE,
    hierarchy_status_id    BIGINT                                  NOT NULL,
    office_type_id         BIGINT                                  NOT NULL,
    setup_date             TIMESTAMP WITHOUT TIME ZONE,
    office_code            VARCHAR(10),
    office_name            VARCHAR(100),
    description            VARCHAR(255),
    CONSTRAINT pk_country_office_hierarchy PRIMARY KEY (id)
);

CREATE TABLE day
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_day PRIMARY KEY (id)
);

CREATE TABLE domain_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    status_name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_domain_status PRIMARY KEY (id)
);

CREATE TABLE employee_core_info
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                BIGINT,
    created_date              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by          BIGINT,
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    home_country_id           BIGINT                                  NOT NULL,
    pin_no                    VARCHAR(255)                            NOT NULL,
    ref_pin                   VARCHAR(255),
    joining_date              date,
    salutation_id             BIGINT,
    first_name                VARCHAR(255)                            NOT NULL,
    middle_name               VARCHAR(50),
    last_name                 VARCHAR(50)                             NOT NULL,
    nick_name                 VARCHAR(50),
    gender_id                 BIGINT,
    employee_dob              date,
    domain_status_id          BIGINT,
    employee_status_id        BIGINT                                  NOT NULL,
    provision_end_date        date,
    cur_job_status_id         BIGINT                                  NOT NULL,
    is_on_deputation          BOOLEAN,
    deputation_end_date       date,
    cur_job_start_date        date,
    expiry_date               date,
    approval_status           VARCHAR(255),
    approval_date             date,
    is_issued_letter          BOOLEAN,
    is_issued_retire_letter   BOOLEAN,
    employee_level_id         BIGINT,
    emp_category_id           BIGINT,
    e_designation_id          BIGINT,
    f_designation_id          BIGINT,
    office_country_id         BIGINT,
    office_info_id            BIGINT,
    program_type_id           BIGINT,
    core_project_id           BIGINT,
    core_program_id           BIGINT,
    department_id             BIGINT,
    supervisor_id             BIGINT,
    assigned_date             date,
    notice_period             BIGINT,
    probation_notice_period   BIGINT,
    working_hour              BIGINT,
    working_day_in_week       BIGINT,
    nominee_form              BIGINT,
    is_expatriate             BOOLEAN,
    country_level_id          BIGINT,
    recruitment_country_id    BIGINT,
    cur_country_join_date     date,
    cur_office_join_date      date,
    contract_start_date       date,
    email_address             VARCHAR(255),
    unit_id                   BIGINT,
    position_id               VARCHAR(255),
    roll_no                   VARCHAR(255),
    recruit_req_no            VARCHAR(255),
    previous_emp_core_info_id BIGINT,
    employee_name             VARCHAR(255),
    national_id_no            VARCHAR(255),
    smart_nid_no              VARCHAR(255),
    slab_id                   BIGINT,
    pay_group_id              BIGINT,
    currency_name             VARCHAR(255),
    is_increment              BOOLEAN,
    is_promotion              BOOLEAN,
    is_leave                  BOOLEAN,
    is_attendance             BOOLEAN,
    joining_date_as_pa        date,
    religion_id               BIGINT,
    is_receive                BOOLEAN,
    is_post_ref_required      BOOLEAN,
    is_post_ref_completed     BOOLEAN,
    is_back_check_completed   BOOLEAN,
    organogram                BIGINT,
    position                  BIGINT,
    ref_erecruit_id           VARCHAR(255),
    tin_type_id               BIGINT,
    tin_number                VARCHAR(255),
    CONSTRAINT pk_employee_core_info PRIMARY KEY (id)
);

CREATE TABLE employee_job_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_employee_job_status PRIMARY KEY (id)
);

CREATE TABLE employee_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    short_name         VARCHAR(255),
    CONSTRAINT pk_employee_status PRIMARY KEY (id)
);

CREATE TABLE entity_category
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    domain_status      BIGINT,
    description        VARCHAR(255),
    entity_name        VARCHAR(255),
    CONSTRAINT pk_entity_category PRIMARY KEY (id)
);

CREATE TABLE family_info
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by           BIGINT,
    created_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by     BIGINT,
    last_modified_date   TIMESTAMP WITHOUT TIME ZONE,
    daughter_no          INTEGER,
    earning_member_no    INTEGER,
    female_no            INTEGER,
    is_family_loan       BOOLEAN,
    is_tax_payer         BOOLEAN,
    male_no              INTEGER,
    other_org_member_no  INTEGER,
    son_no               INTEGER,
    house_hold_head_name VARCHAR(50),
    member_info_id       BIGINT,
    CONSTRAINT pk_family_info PRIMARY KEY (id)
);

CREATE TABLE frequency
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    frequency_name     VARCHAR(255),
    CONSTRAINT pk_frequency PRIMARY KEY (id)
);

CREATE TABLE group_close_reason
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT pk_group_close_reason PRIMARY KEY (id)
);

CREATE TABLE group_infos
(
    id                              BIGINT                      NOT NULL,
    created_by                      BIGINT,
    created_date                    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by                BIGINT,
    last_modified_date              TIMESTAMP WITHOUT TIME ZONE,
    group_code                      VARCHAR(255),
    group_name                      VARCHAR(255),
    assignedpo_id                   BIGINT                      NOT NULL,
    orientation_date                TIMESTAMP WITHOUT TIME ZONE,
    group_creation_date             TIMESTAMP WITHOUT TIME ZONE,
    lastpoassigned_date             TIMESTAMP WITHOUT TIME ZONE,
    group_reference_number          VARCHAR(25),
    spot_address                    VARCHAR(255),
    group_status_id                 BIGINT                      NOT NULL,
    domain_status_id                BIGINT                      NOT NULL,
    close_reason_id                 BIGINT,
    closing_date                    TIMESTAMP WITHOUT TIME ZONE,
    meeting_day_id                  BIGINT                      NOT NULL,
    meeting_time                    VARCHAR(255),
    demarcation_area                VARCHAR(255),
    week_number                     BIGINT,
    loan_collection_frequency_id    BIGINT                      NOT NULL,
    loan_collection_start_date      TIMESTAMP WITHOUT TIME ZONE,
    savings_collection_frequency_id BIGINT                      NOT NULL,
    savings_collection_start_date   TIMESTAMP WITHOUT TIME ZONE,
    next_collection_date            TIMESTAMP WITHOUT TIME ZONE,
    branch_info_id                  BIGINT,
    project_info_id                 BIGINT                      NOT NULL,
    scanned_form                    VARCHAR(255),
    is_transferred_group            BOOLEAN,
    group_category_id               BIGINT,
    vo_category_id                  BIGINT,
    service_territory_id            BIGINT,
    applicable_gender_id            BIGINT,
    longitude                       VARCHAR(255),
    latitude                        VARCHAR(255),
    CONSTRAINT pk_group_infos PRIMARY KEY (id)
);

CREATE TABLE group_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_group_status PRIMARY KEY (id)
);

CREATE TABLE guarantor_info
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    age                INTEGER,
    domain_status_id   INTEGER,
    date_of_birth      TIMESTAMP WITHOUT TIME ZONE,
    guarantor_name     VARCHAR(50)                             NOT NULL,
    national_id        VARCHAR(255),
    scanned_file_name  VARCHAR(255),
    member_info_id     BIGINT,
    relationship_id    BIGINT,
    CONSTRAINT pk_guarantor_info PRIMARY KEY (id)
);

CREATE TABLE interest_calculation_frequency
(
    id                 BIGINT                      NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    frequency_name     VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_interest_calculation_frequency PRIMARY KEY (id)
);

CREATE TABLE interest_calculation_method
(
    id                 BIGINT                      NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    method_name        VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_interest_calculation_method PRIMARY KEY (id)
);

CREATE TABLE interest_credit_frequency
(
    id                 BIGINT                      NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    frequency_name     VARCHAR(255)                NOT NULL,
    CONSTRAINT pk_interest_credit_frequency PRIMARY KEY (id)
);

CREATE TABLE interest_provision_frequency
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    frequency_name     VARCHAR(255),
    CONSTRAINT pk_interest_provision_frequency PRIMARY KEY (id)
);

CREATE TABLE interest_rate_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    rate_name          VARCHAR(255),
    CONSTRAINT pk_interest_rate_type PRIMARY KEY (id)
);

CREATE TABLE locale_message
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    locale             VARCHAR(255),
    content            VARCHAR(255),
    version            VARCHAR(255),
    CONSTRAINT pk_locale_message PRIMARY KEY (id)
);

CREATE TABLE member_address
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    address_title_id   BIGINT                                  NOT NULL,
    address            VARCHAR(255),
    country_id         BIGINT,
    city_id            BIGINT,
    thana_id           BIGINT,
    zip_code           VARCHAR(8),
    contact_info_id    BIGINT,
    CONSTRAINT pk_member_address PRIMARY KEY (id)
);

CREATE TABLE member_info
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                  BIGINT,
    created_date                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by            BIGINT,
    last_modified_date          TIMESTAMP WITHOUT TIME ZONE,
    country_id                  BIGINT,
    branch_info_id              BIGINT,
    assignedpo_id               BIGINT,
    project_info_id             BIGINT                                  NOT NULL,
    group_info_id               BIGINT,
    member_no                   VARCHAR(255),
    reference_no                VARCHAR(255),
    group_ref_no                VARCHAR(255),
    member_name                 VARCHAR(50)                             NOT NULL,
    f_name                      VARCHAR(255),
    m_name                      VARCHAR(255),
    l_name                      VARCHAR(255),
    application_date            TIMESTAMP WITHOUT TIME ZONE,
    survey_report_no            VARCHAR(255),
    membership_date             TIMESTAMP WITHOUT TIME ZONE,
    lastpoassigned_date         TIMESTAMP WITHOUT TIME ZONE,
    member_status_id            BIGINT                                  NOT NULL,
    expired_date                TIMESTAMP WITHOUT TIME ZONE,
    closing_date                TIMESTAMP WITHOUT TIME ZONE,
    domain_status_id            BIGINT,
    is_transferred_member       BOOLEAN,
    close_reason_id             BIGINT,
    transfer_transaction_ref_no VARCHAR(255),
    loan_cycle_no               BIGINT,
    member_custom_field         VARCHAR(255),
    personal_info_id            BIGINT,
    guarantor_info_id           BIGINT,
    family_info_id              BIGINT,
    contact_info_id             BIGINT,
    signature_id                VARCHAR(255),
    documents_id                BIGINT,
    member_classification_id    BIGINT,
    referred_by                 VARCHAR(255),
    passbook_no                 VARCHAR(255),
    tin_number                  VARCHAR(12),
    academic_qualification_id   BIGINT,
    bank_id                     BIGINT,
    bank_branch_id              BIGINT,
    bank_account_number         VARCHAR(255),
    routing_number              VARCHAR(255),
    incident_status             INTEGER,
    buffer_id                   VARCHAR(255),
    api_data_source_id          INTEGER,
    uuid_no                     BIGINT,
    CONSTRAINT pk_member_info PRIMARY KEY (id)
);

CREATE TABLE member_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    name               VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_member_status PRIMARY KEY (id)
);

CREATE TABLE membership_document
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                BIGINT,
    created_date              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by          BIGINT,
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    driving_license_reference VARCHAR(255),
    membership_form_reference VARCHAR(255),
    national_id_reference     VARCHAR(255),
    other_form_reference      VARCHAR(255),
    passport_reference        VARCHAR(255),
    photo_id_reference        VARCHAR(255),
    survey_form_reference     VARCHAR(255),
    member_info_id            BIGINT,
    CONSTRAINT pk_membership_document PRIMARY KEY (id)
);

CREATE TABLE nominee_info
(
    id                 BIGINT                      NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    age                INTEGER,
    share_percent      DOUBLE PRECISION,
    date_of_birth      TIMESTAMP WITHOUT TIME ZONE,
    contact_no         VARCHAR(255),
    name               VARCHAR(255),
    national_id        VARCHAR(255),
    passport_no        VARCHAR(255),
    photo_id_no        VARCHAR(255),
    photo_reference    VARCHAR(255),
    smart_card_id      VARCHAR(255),
    member_info_id     BIGINT,
    relationship_id    BIGINT,
    CONSTRAINT pk_nominee_info PRIMARY KEY (id)
);

CREATE TABLE occupation
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    name               VARCHAR(255),
    CONSTRAINT pk_occupation PRIMARY KEY (id)
);

CREATE TABLE office_address
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    address_line1      VARCHAR(255),
    address_line2      VARCHAR(255),
    city_id            BIGINT,
    zip_code           VARCHAR(255),
    status_id          BIGINT,
    province_info_id   BIGINT,
    division_info_id   BIGINT,
    district_info_id   BIGINT,
    tehsil_info_id     BIGINT,
    CONSTRAINT pk_office_address PRIMARY KEY (id)
);

CREATE TABLE office_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    office_type_code   VARCHAR(10)                             NOT NULL,
    office_type_name   VARCHAR(100)                            NOT NULL,
    hierarchy_level    INTEGER                                 NOT NULL,
    description        VARCHAR(255),
    office_op_type     VARCHAR(255),
    CONSTRAINT pk_office_type PRIMARY KEY (id)
);

CREATE TABLE operation_type
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            BIGINT,
    created_date          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by      BIGINT,
    last_modified_date    TIMESTAMP WITHOUT TIME ZONE,
    operation_code        VARCHAR(255),
    operation_description VARCHAR(255),
    CONSTRAINT pk_operation_type PRIMARY KEY (id)
);

CREATE TABLE organization_department
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    dept_code          VARCHAR(255),
    description        VARCHAR(255),
    name               VARCHAR(255),
    status             VARCHAR(255),
    CONSTRAINT pk_organization_department PRIMARY KEY (id)
);

CREATE TABLE other_organization_loan
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    loan_amount        FLOAT,
    family_info_id     BIGINT,
    organization_name  VARCHAR(255),
    CONSTRAINT pk_other_organization_loan PRIMARY KEY (id)
);

CREATE TABLE passbook_info
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    passbook_no        VARCHAR(20),
    issue_date         date                                    NOT NULL,
    passbook_status_id BIGINT                                  NOT NULL,
    passbook_price     DOUBLE PRECISION                        NOT NULL,
    is_deleted         BOOLEAN                                 NOT NULL,
    date_created       TIMESTAMP WITHOUT TIME ZONE,
    status_change      TIMESTAMP WITHOUT TIME ZONE,
    transaction_no     VARCHAR(255),
    member_info_id     BIGINT,
    CONSTRAINT pk_passbook_info PRIMARY KEY (id)
);

CREATE TABLE passbook_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    description        VARCHAR(255),
    name               VARCHAR(255),
    CONSTRAINT pk_passbook_status PRIMARY KEY (id)
);

CREATE TABLE personal_info
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                BIGINT,
    created_date              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by          BIGINT,
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    salutation_id             BIGINT,
    national_id               VARCHAR(17),
    smart_card_id             VARCHAR(10),
    passport_no               VARCHAR(30),
    driving_license_no        VARCHAR(30),
    photo_id_no               VARCHAR(30),
    gender_id                 BIGINT                                  NOT NULL,
    marital_status_id         BIGINT                                  NOT NULL,
    age                       INTEGER,
    biometric_status          INTEGER,
    occupation_id             BIGINT,
    date_of_birth             TIMESTAMP WITHOUT TIME ZONE,
    father_name               VARCHAR(50),
    mother_name               VARCHAR(50),
    spouse_name               VARCHAR(50),
    sp_date_of_birth          TIMESTAMP WITHOUT TIME ZONE,
    sp_national_id            VARCHAR(17),
    sp_smart_card_id          VARCHAR(10),
    sp_passport_no            VARCHAR(30),
    sp_photo_id_no            VARCHAR(30),
    bikash_wallet_no          VARCHAR(255),
    rocket_wallet_no          VARCHAR(255),
    referral_info_id          BIGINT,
    photo_reference           VARCHAR(255),
    other_id_type_id          SMALLINT,
    other_id_type_no          VARCHAR(255),
    expiry_date               TIMESTAMP WITHOUT TIME ZONE,
    place_of_issuing_country  VARCHAR(255),
    is_person_with_disability BOOLEAN,
    member_info_id            BIGINT,
    CONSTRAINT pk_personal_info PRIMARY KEY (id)
);

CREATE TABLE physical_office_info
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                 BIGINT,
    created_date               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by           BIGINT,
    last_modified_date         TIMESTAMP WITHOUT TIME ZONE,
    office_code                VARCHAR(15)                             NOT NULL,
    office_ref_code            VARCHAR(255),
    office_name                VARCHAR(255),
    office_type_id             BIGINT,
    area_type                  VARCHAR(255),
    setup_date                 date,
    effective_date             date,
    registered_address_id      BIGINT,
    business_address_id        BIGINT,
    office_status_id           BIGINT,
    office_country_id          BIGINT,
    parent_office_id           BIGINT,
    mobile_no                  VARCHAR(255),
    is_hr_office               BOOLEAN,
    is_mf_office               BOOLEAN,
    is_dev_office              BOOLEAN,
    is_upazila_accounts_office BOOLEAN,
    is_indp                    BOOLEAN,
    verify_tb                  BOOLEAN,
    verify_portfolio           BOOLEAN,
    verify_savings             BOOLEAN,
    office_hierarchy_id        BIGINT,
    reporting_to_id            BIGINT,
    mf_branch_id               VARCHAR(255),
    mf_ref_code                VARCHAR(255),
    dev_ref_code               VARCHAR(255),
    has_operation              BOOLEAN                                 NOT NULL,
    bkash_wallet_no            VARCHAR(255),
    operation_category         VARCHAR(255),
    parent_project_id          BIGINT,
    CONSTRAINT pk_physical_office_info PRIMARY KEY (id)
);

CREATE TABLE program_info
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by          BIGINT,
    created_date        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by    BIGINT,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    program_code        VARCHAR(255),
    program_ref_code    VARCHAR(255),
    program_name        VARCHAR(150)                            NOT NULL,
    program_short_name  VARCHAR(150),
    program_description VARCHAR(255),
    operation_type_id   BIGINT,
    program_type_id     BIGINT,
    entity_category_id  BIGINT,
    has_field_office    BOOLEAN,
    setup_date          date                                    NOT NULL,
    effective_date      date                                    NOT NULL,
    domain_status_id    BIGINT,
    CONSTRAINT pk_program_info PRIMARY KEY (id)
);

CREATE TABLE program_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    type_name          VARCHAR(255),
    description        VARCHAR(255),
    domain_status_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_program_type PRIMARY KEY (id)
);

CREATE TABLE project_info
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by             BIGINT,
    created_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by       BIGINT,
    last_modified_date     TIMESTAMP WITHOUT TIME ZONE,
    proposal_id            VARCHAR(255),
    project_country_id     BIGINT,
    project_code           VARCHAR(255),
    project_ref_code       VARCHAR(255),
    project_name           VARCHAR(255)                            NOT NULL,
    project_description    VARCHAR(255),
    project_short_code     VARCHAR(255),
    project_setup_date     date,
    project_effective_date date,
    project_start_date     date,
    project_end_date       date,
    domain_status_id       BIGINT,
    program_info_id        BIGINT,
    book_closing           BOOLEAN,
    parent_project_info_id BIGINT,
    department_id          BIGINT,
    is_independent         BOOLEAN,
    is_overhead            BOOLEAN,
    ho_type                VARCHAR(255),
    bo_type                VARCHAR(255),
    mf_project_ref_code    VARCHAR(255),
    is_ngo_beuro           BOOLEAN,
    beuro_from_date        date,
    beuro_to_date          date,
    is_trendx_project      BOOLEAN,
    is_smart_collection    BOOLEAN,
    has_mf_operation       BOOLEAN                                 NOT NULL,
    project_status         VARCHAR(255),
    start_month            INTEGER,
    end_month              INTEGER,
    mf_end_month           INTEGER,
    has_fin_operation      BOOLEAN,
    source_of_fund_id      BIGINT,
    remarks                TEXT,
    foreign_currency       VARCHAR(255),
    local_currency         VARCHAR(255),
    foreign_amount         BIGINT,
    local_amount           BIGINT,
    signing_date           date,
    CONSTRAINT pk_project_info PRIMARY KEY (id)
);

CREATE TABLE relationship
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(50)                             NOT NULL,
    description        VARCHAR(255),
    is_relative        BOOLEAN,
    status_id          BIGINT,
    CONSTRAINT pk_relationship PRIMARY KEY (id)
);

CREATE TABLE salutation
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT pk_salutation PRIMARY KEY (id)
);

CREATE TABLE savings_account
(
    id                             VARCHAR(255)                NOT NULL,
    created_by                     BIGINT,
    created_date                   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by               BIGINT,
    last_modified_date             TIMESTAMP WITHOUT TIME ZONE,
    country_id                     BIGINT,
    account_no                     VARCHAR(255),
    account_name                   VARCHAR(255),
    account_type_id                BIGINT,
    creation_date                  TIMESTAMP WITHOUT TIME ZONE,
    closing_date                   TIMESTAMP WITHOUT TIME ZONE,
    initial_deposit                DOUBLE PRECISION,
    installment_amount             DOUBLE PRECISION,
    office_info_id                 BIGINT,
    group_info_id                  BIGINT,
    project_info_id                BIGINT,
    savings_product_id             BIGINT,
    interest_rate                  DOUBLE PRECISION,
    calculation_frequency_id       BIGINT,
    provision_frequency_id         BIGINT,
    calculation_method_id          BIGINT,
    credit_frequency_id            BIGINT,
    account_status_id              BIGINT,
    portfolio_status_id            BIGINT,
    domain_status_id               BIGINT,
    savings_balance                DOUBLE PRECISION,
    provisioned_interest           DOUBLE PRECISION,
    calculated_interest            DOUBLE PRECISION,
    is_transferred_savings         BOOLEAN,
    has_matched_fund               BOOLEAN,
    match_fund_max_amount          DOUBLE PRECISION,
    match_ratio                    DOUBLE PRECISION,
    match_fund_expired_date        TIMESTAMP WITHOUT TIME ZONE,
    cohort_mapping_id              BIGINT,
    next_collection_date           TIMESTAMP WITHOUT TIME ZONE,
    last_transferred_date          TIMESTAMP WITHOUT TIME ZONE,
    current_savings_account_type   INTEGER,
    current_account_mobile         VARCHAR(255),
    otp_send_type                  INTEGER,
    last_interest_calculation_date TIMESTAMP WITHOUT TIME ZONE,
    is_inter_member_transferred    BOOLEAN,
    uid_cycle_no                   INTEGER,
    uid_status                     INTEGER,
    member_info_id                 BIGINT,
    CONSTRAINT pk_savings_account PRIMARY KEY (id)
);

CREATE TABLE savings_account_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT pk_savings_account_status PRIMARY KEY (id)
);

CREATE TABLE savings_account_type
(
    id                 BIGINT                      NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    type_name          VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_savings_account_type PRIMARY KEY (id)
);

CREATE TABLE savings_portfolio_status
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255),
    CONSTRAINT pk_savings_portfolio_status PRIMARY KEY (id)
);

CREATE TABLE savings_product
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                  BIGINT,
    created_date                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by            BIGINT,
    last_modified_date          TIMESTAMP WITHOUT TIME ZONE,
    country_id                  BIGINT                                  NOT NULL,
    product_code                VARCHAR(255)                            NOT NULL,
    product_ref_code            VARCHAR(255),
    product_name                VARCHAR(150)                            NOT NULL,
    setup_date                  date                                    NOT NULL,
    product_type_id             BIGINT                                  NOT NULL,
    interest_rate               DOUBLE PRECISION                        NOT NULL,
    rate_type_id                BIGINT                                  NOT NULL,
    description                 VARCHAR(255),
    savings_product_sub_type_id BIGINT,
    savings_product_category_id INTEGER                                 NOT NULL,
    client_percentage_lower     INTEGER                                 NOT NULL,
    client_percentage_upper     INTEGER                                 NOT NULL,
    profit_payment_day          INTEGER,
    has_match_fund              BOOLEAN                                 NOT NULL,
    domain_status_id            BIGINT,
    CONSTRAINT pk_savings_product PRIMARY KEY (id)
);

CREATE TABLE savings_product_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    type_name          VARCHAR(255),
    description        VARCHAR(255),
    CONSTRAINT pk_savings_product_type PRIMARY KEY (id)
);

CREATE TABLE signature
(
    id                  VARCHAR(255)                NOT NULL,
    created_by          BIGINT,
    created_date        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_modified_by    BIGINT,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    signature_reference VARCHAR(255)                NOT NULL,
    member_info_id      BIGINT,
    CONSTRAINT pk_signature PRIMARY KEY (id)
);

ALTER TABLE close_reason
    ADD CONSTRAINT uc_close_reason_name UNIQUE (name);

ALTER TABLE country
    ADD CONSTRAINT uc_country_code UNIQUE (code);

ALTER TABLE country
    ADD CONSTRAINT uc_country_name UNIQUE (name);

ALTER TABLE day
    ADD CONSTRAINT uc_day_name UNIQUE (name);

ALTER TABLE domain_status
    ADD CONSTRAINT uc_domain_status_status_name UNIQUE (status_name);

ALTER TABLE group_close_reason
    ADD CONSTRAINT uc_group_close_reason_name UNIQUE (name);

ALTER TABLE group_status
    ADD CONSTRAINT uc_group_status_name UNIQUE (name);

ALTER TABLE interest_calculation_frequency
    ADD CONSTRAINT uc_interest_calculation_frequency_frequency_name UNIQUE (frequency_name);

ALTER TABLE interest_calculation_method
    ADD CONSTRAINT uc_interest_calculation_method_method_name UNIQUE (method_name);

ALTER TABLE interest_credit_frequency
    ADD CONSTRAINT uc_interest_credit_frequency_frequency_name UNIQUE (frequency_name);

ALTER TABLE member_info
    ADD CONSTRAINT uc_member_info_contact_info UNIQUE (contact_info_id);

ALTER TABLE member_info
    ADD CONSTRAINT uc_member_info_documents UNIQUE (documents_id);

ALTER TABLE member_info
    ADD CONSTRAINT uc_member_info_family_info UNIQUE (family_info_id);

ALTER TABLE member_info
    ADD CONSTRAINT uc_member_info_guarantor_info UNIQUE (guarantor_info_id);

ALTER TABLE member_info
    ADD CONSTRAINT uc_member_info_personal_info UNIQUE (personal_info_id);

ALTER TABLE member_info
    ADD CONSTRAINT uc_member_info_signature UNIQUE (signature_id);

ALTER TABLE member_status
    ADD CONSTRAINT uc_member_status_name UNIQUE (name);

ALTER TABLE office_type
    ADD CONSTRAINT uc_office_type_hierarchy_level UNIQUE (hierarchy_level);

ALTER TABLE office_type
    ADD CONSTRAINT uc_office_type_office_type_code UNIQUE (office_type_code);

ALTER TABLE office_type
    ADD CONSTRAINT uc_office_type_office_type_name UNIQUE (office_type_name);

ALTER TABLE program_info
    ADD CONSTRAINT uc_program_info_program_name UNIQUE (program_name);

ALTER TABLE relationship
    ADD CONSTRAINT uc_relationship_name UNIQUE (name);

ALTER TABLE salutation
    ADD CONSTRAINT uc_salutation_name UNIQUE (name);

ALTER TABLE savings_account_status
    ADD CONSTRAINT uc_savings_account_status_name UNIQUE (name);

ALTER TABLE savings_portfolio_status
    ADD CONSTRAINT uc_savings_portfolio_status_name UNIQUE (name);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE contact_info
    ADD CONSTRAINT FK_CONTACT_INFO_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE country_office_hierarchy
    ADD CONSTRAINT FK_COUNTRY_OFFICE_HIERARCHY_ON_COUNTRY_OF_OFFICE FOREIGN KEY (country_of_office_id) REFERENCES country (id);

ALTER TABLE country_office_hierarchy
    ADD CONSTRAINT FK_COUNTRY_OFFICE_HIERARCHY_ON_HIERARCHY_STATUS FOREIGN KEY (hierarchy_status_id) REFERENCES domain_status (id);

ALTER TABLE country_office_hierarchy
    ADD CONSTRAINT FK_COUNTRY_OFFICE_HIERARCHY_ON_OFFICE_TYPE FOREIGN KEY (office_type_id) REFERENCES office_type (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_CORE_PROGRAM FOREIGN KEY (core_program_id) REFERENCES program_info (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_CORE_PROJECT FOREIGN KEY (core_project_id) REFERENCES project_info (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_CUR_JOB_STATUS FOREIGN KEY (cur_job_status_id) REFERENCES employee_job_status (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES organization_department (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_EMPLOYEE_STATUS FOREIGN KEY (employee_status_id) REFERENCES employee_status (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_OFFICE_INFO FOREIGN KEY (office_info_id) REFERENCES physical_office_info (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_PROGRAM_TYPE FOREIGN KEY (program_type_id) REFERENCES program_type (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_SALUTATION FOREIGN KEY (salutation_id) REFERENCES salutation (id);

ALTER TABLE employee_core_info
    ADD CONSTRAINT FK_EMPLOYEE_CORE_INFO_ON_SUPERVISOR FOREIGN KEY (supervisor_id) REFERENCES employee_core_info (id);

ALTER TABLE family_info
    ADD CONSTRAINT FK_FAMILY_INFO_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_ASSIGNEDPO FOREIGN KEY (assignedpo_id) REFERENCES employee_core_info (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_BRANCH_INFO FOREIGN KEY (branch_info_id) REFERENCES physical_office_info (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_CLOSE_REASON FOREIGN KEY (close_reason_id) REFERENCES group_close_reason (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_DOMAIN_STATUS FOREIGN KEY (domain_status_id) REFERENCES domain_status (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_GROUP_STATUS FOREIGN KEY (group_status_id) REFERENCES group_status (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_LOAN_COLLECTION_FREQUENCY FOREIGN KEY (loan_collection_frequency_id) REFERENCES collection_frequency (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_MEETING_DAY FOREIGN KEY (meeting_day_id) REFERENCES day (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_PROJECT_INFO FOREIGN KEY (project_info_id) REFERENCES project_info (id);

ALTER TABLE group_infos
    ADD CONSTRAINT FK_GROUP_INFOS_ON_SAVINGS_COLLECTION_FREQUENCY FOREIGN KEY (savings_collection_frequency_id) REFERENCES collection_frequency (id);

ALTER TABLE guarantor_info
    ADD CONSTRAINT FK_GUARANTOR_INFO_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE membership_document
    ADD CONSTRAINT FK_MEMBERSHIP_DOCUMENT_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE member_address
    ADD CONSTRAINT FK_MEMBER_ADDRESS_ON_ADDRESS_TITLE FOREIGN KEY (address_title_id) REFERENCES address_title (id);

ALTER TABLE member_address
    ADD CONSTRAINT FK_MEMBER_ADDRESS_ON_CONTACT_INFO FOREIGN KEY (contact_info_id) REFERENCES contact_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_ASSIGNEDPO FOREIGN KEY (assignedpo_id) REFERENCES employee_core_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_BRANCH_INFO FOREIGN KEY (branch_info_id) REFERENCES physical_office_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_CLOSE_REASON FOREIGN KEY (close_reason_id) REFERENCES close_reason (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_CONTACT_INFO FOREIGN KEY (contact_info_id) REFERENCES contact_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_DOCUMENTS FOREIGN KEY (documents_id) REFERENCES membership_document (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_DOMAIN_STATUS FOREIGN KEY (domain_status_id) REFERENCES domain_status (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_FAMILY_INFO FOREIGN KEY (family_info_id) REFERENCES family_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_GROUP_INFO FOREIGN KEY (group_info_id) REFERENCES group_infos (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_GUARANTOR_INFO FOREIGN KEY (guarantor_info_id) REFERENCES guarantor_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_MEMBER_STATUS FOREIGN KEY (member_status_id) REFERENCES member_status (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_PERSONAL_INFO FOREIGN KEY (personal_info_id) REFERENCES personal_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_PROJECT_INFO FOREIGN KEY (project_info_id) REFERENCES project_info (id);

ALTER TABLE member_info
    ADD CONSTRAINT FK_MEMBER_INFO_ON_SIGNATURE FOREIGN KEY (signature_id) REFERENCES signature (id);

ALTER TABLE nominee_info
    ADD CONSTRAINT FK_NOMINEE_INFO_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE nominee_info
    ADD CONSTRAINT FK_NOMINEE_INFO_ON_RELATIONSHIP FOREIGN KEY (relationship_id) REFERENCES relationship (id);

ALTER TABLE office_address
    ADD CONSTRAINT FK_OFFICE_ADDRESS_ON_CITY FOREIGN KEY (city_id) REFERENCES city (id);

ALTER TABLE office_address
    ADD CONSTRAINT FK_OFFICE_ADDRESS_ON_STATUS FOREIGN KEY (status_id) REFERENCES domain_status (id);

ALTER TABLE other_organization_loan
    ADD CONSTRAINT FK_OTHER_ORGANIZATION_LOAN_ON_FAMILY_INFO FOREIGN KEY (family_info_id) REFERENCES family_info (id);

ALTER TABLE passbook_info
    ADD CONSTRAINT FK_PASSBOOK_INFO_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE passbook_info
    ADD CONSTRAINT FK_PASSBOOK_INFO_ON_PASSBOOK_STATUS FOREIGN KEY (passbook_status_id) REFERENCES passbook_status (id);

ALTER TABLE personal_info
    ADD CONSTRAINT FK_PERSONAL_INFO_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE personal_info
    ADD CONSTRAINT FK_PERSONAL_INFO_ON_OCCUPATION FOREIGN KEY (occupation_id) REFERENCES occupation (id);

ALTER TABLE personal_info
    ADD CONSTRAINT FK_PERSONAL_INFO_ON_SALUTATION FOREIGN KEY (salutation_id) REFERENCES salutation (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_BUSINESS_ADDRESS FOREIGN KEY (business_address_id) REFERENCES office_address (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_OFFICE_COUNTRY FOREIGN KEY (office_country_id) REFERENCES country (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_OFFICE_HIERARCHY FOREIGN KEY (office_hierarchy_id) REFERENCES country_office_hierarchy (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_OFFICE_TYPE FOREIGN KEY (office_type_id) REFERENCES office_type (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_PARENT_OFFICE FOREIGN KEY (parent_office_id) REFERENCES physical_office_info (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_REGISTERED_ADDRESS FOREIGN KEY (registered_address_id) REFERENCES office_address (id);

ALTER TABLE physical_office_info
    ADD CONSTRAINT FK_PHYSICAL_OFFICE_INFO_ON_REPORTING_TO FOREIGN KEY (reporting_to_id) REFERENCES physical_office_info (id);

ALTER TABLE program_info
    ADD CONSTRAINT FK_PROGRAM_INFO_ON_ENTITY_CATEGORY FOREIGN KEY (entity_category_id) REFERENCES entity_category (id);

ALTER TABLE program_info
    ADD CONSTRAINT FK_PROGRAM_INFO_ON_OPERATION_TYPE FOREIGN KEY (operation_type_id) REFERENCES operation_type (id);

ALTER TABLE program_info
    ADD CONSTRAINT FK_PROGRAM_INFO_ON_PROGRAM_TYPE FOREIGN KEY (program_type_id) REFERENCES program_type (id);

ALTER TABLE program_type
    ADD CONSTRAINT FK_PROGRAM_TYPE_ON_DOMAIN_STATUS FOREIGN KEY (domain_status_id) REFERENCES domain_status (id);

ALTER TABLE project_info
    ADD CONSTRAINT FK_PROJECT_INFO_ON_DOMAIN_STATUS FOREIGN KEY (domain_status_id) REFERENCES domain_status (id);

ALTER TABLE project_info
    ADD CONSTRAINT FK_PROJECT_INFO_ON_PROGRAM_INFO FOREIGN KEY (program_info_id) REFERENCES program_info (id);

ALTER TABLE project_info
    ADD CONSTRAINT FK_PROJECT_INFO_ON_PROJECT_COUNTRY FOREIGN KEY (project_country_id) REFERENCES country (id);

ALTER TABLE relationship
    ADD CONSTRAINT FK_RELATIONSHIP_ON_STATUS FOREIGN KEY (status_id) REFERENCES domain_status (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_ACCOUNT_STATUS FOREIGN KEY (account_status_id) REFERENCES savings_account_status (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_ACCOUNT_TYPE FOREIGN KEY (account_type_id) REFERENCES savings_account_type (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_CALCULATION_FREQUENCY FOREIGN KEY (calculation_frequency_id) REFERENCES interest_calculation_frequency (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_CALCULATION_METHOD FOREIGN KEY (calculation_method_id) REFERENCES interest_calculation_method (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_CREDIT_FREQUENCY FOREIGN KEY (credit_frequency_id) REFERENCES interest_credit_frequency (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_DOMAIN_STATUS FOREIGN KEY (domain_status_id) REFERENCES domain_status (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_PORTFOLIO_STATUS FOREIGN KEY (portfolio_status_id) REFERENCES savings_portfolio_status (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_PROJECT_INFO FOREIGN KEY (project_info_id) REFERENCES project_info (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_PROVISION_FREQUENCY FOREIGN KEY (provision_frequency_id) REFERENCES interest_provision_frequency (id);

ALTER TABLE savings_account
    ADD CONSTRAINT FK_SAVINGS_ACCOUNT_ON_SAVINGS_PRODUCT FOREIGN KEY (savings_product_id) REFERENCES savings_product (id);

ALTER TABLE savings_product
    ADD CONSTRAINT FK_SAVINGS_PRODUCT_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE savings_product
    ADD CONSTRAINT FK_SAVINGS_PRODUCT_ON_PRODUCT_TYPE FOREIGN KEY (product_type_id) REFERENCES savings_product_type (id);

ALTER TABLE savings_product
    ADD CONSTRAINT FK_SAVINGS_PRODUCT_ON_RATE_TYPE FOREIGN KEY (rate_type_id) REFERENCES interest_rate_type (id);

ALTER TABLE signature
    ADD CONSTRAINT FK_SIGNATURE_ON_MEMBER_INFO FOREIGN KEY (member_info_id) REFERENCES member_info (id);

CREATE TABLE public.mode_of_payment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         BIGINT,
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    mode_description   VARCHAR(255),
    mode_name          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_mode_of_payment PRIMARY KEY (id)
);

ALTER TABLE public.mode_of_payment
    ADD CONSTRAINT uc_mode_of_payment_mode_name UNIQUE (mode_name);