server:
  port: 8081

spring:
  application:
    name: current-savings-service
  datasource:
    url: jdbc:postgresql://localhost:5432/current_savings
    username: postgres
    password: root
#    url: jdbc:postgresql://10.42.65.131:4550/sbicloud_bd_smalldb
#    username: bits
#    password: biTS@#123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: postgres
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        order_updates: true
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    enabled: true
    locations: classpath:resources/db/V2__.sql
    baseline-on-migrate: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30 # in seconds
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  config: classpath:log/logback-alpha.xml
  level:
    org.hibernate.orm: INFO
